feature: waterfalls
staging_table: cabd.waterfall_updates

column_types:
  cabd_id: uuid
  fall_name_en: varchar
  fall_name_fr: varchar
  waterbody_name_en: varchar
  waterbody_name_fr: varchar
  province_territory_code: varchar
  fall_height_m: real
  comments: text
  use_analysis: boolean
  latitude: numeric
  longitude: numeric
  entry_classification: varchar
  data_source_short_name: varchar
  status: varchar
  reviewer_comments: varchar
  submitted_on: timestamp with time zone

## coded value transforms will be later

#  passability_status_code: smallint
#  waterfall_type_code: smallint