--THIS SCRIPT IS STILL A WORK IN PROGRESS

-- make the necessary data source attribute tracking tables
CREATE TABLE cabd.data_source(
  id uuid not null primary key,
  name varchar,
  version_date date,
  version_number varchar,
  source varchar,
  comments varchar
);

-- dams data sources
insert into cabd.data_source (id, name, version_date) 
select uuid_generate_v4(), a.data_source, '2021-03-31'
from (
select distinct data_source from dams.dams_medium_large 
where data_source is not null
) a;

-- create dams attribute source table
CREATE TABLE dams.dams_medium_large_attribute_source (
	cabd_id uuid NOT NULL primary key references dams.dams_medium_large,
	dam_name_en_ds uuid REFERENCES cabd.data_source(id),
	dam_name_en_fs varchar,
	dam_name_fr_ds uuid REFERENCES cabd.data_source(id),
	dam_name_fr_fs varchar,
	waterbody_name_en_ds uuid REFERENCES cabd.data_source(id),
	waterbody_name_en_fs varchar,
	waterbody_name_fr_ds uuid REFERENCES cabd.data_source(id),
	waterbody_name_fr_fs varchar,
	reservoir_name_en_ds uuid REFERENCES cabd.data_source(id),
	reservoir_name_en_fs varchar,
	reservoir_name_fr_ds uuid REFERENCES cabd.data_source(id),
	reservoir_name_fr_fs varchar,
	watershed_group_code_ds uuid REFERENCES cabd.data_source(id),
	watershed_group_code_fs varchar,
	nhn_workunit_id_ds uuid REFERENCES cabd.data_source(id),
	nhn_workunit_id_fs varchar,
	province_territory_code_ds uuid REFERENCES cabd.data_source(id),
	province_territory_code_fs varchar,
	nearest_municipality_ds uuid REFERENCES cabd.data_source(id),
	nearest_municipality_fs varchar,
	owner_ds uuid REFERENCES cabd.data_source(id),
	owner_fs varchar,
	ownership_type_code_ds uuid REFERENCES cabd.data_source(id),
	ownership_type_code_fs varchar,
	province_compliance_status_ds uuid REFERENCES cabd.data_source(id),
	province_compliance_status_fs varchar,
	federal_compliance_status_ds uuid REFERENCES cabd.data_source(id),
	federal_compliance_status_fs varchar,
	operating_note_ds uuid REFERENCES cabd.data_source(id),
	operating_note_fs varchar, 
	operating_status_code_ds uuid REFERENCES cabd.data_source(id),
	operating_status_code_fs varchar,
	use_code_ds uuid REFERENCES cabd.data_source(id),
	use_code_fs varchar,
	use_irrigation_code_ds uuid REFERENCES cabd.data_source(id),
	use_irrigation_code_fs varchar,
	use_electricity_code_ds uuid REFERENCES cabd.data_source(id),
	use_electricity_code_fs varchar,
	use_supply_code_ds uuid REFERENCES cabd.data_source(id),
	use_supply_code_fs varchar,
	use_floodcontrol_code_ds uuid REFERENCES cabd.data_source(id),
	use_floodcontrol_code_fs varchar,
	use_recreation_code_ds uuid REFERENCES cabd.data_source(id),
	use_recreation_code_fs varchar,
	use_navigation_code_ds uuid REFERENCES cabd.data_source(id),
	use_navigation_code_fs varchar,
	use_fish_code_ds uuid REFERENCES cabd.data_source(id),
	use_fish_code_fs varchar,
	use_pollution_code_ds uuid REFERENCES cabd.data_source(id),
	use_pollution_code_fs varchar,
	use_invasivespecies_code_ds uuid REFERENCES cabd.data_source(id),
	use_invasivespecies_code_fs varchar,
	use_other_code_ds uuid REFERENCES cabd.data_source(id),
	use_other_code_fs varchar,
	lake_control_code_ds uuid REFERENCES cabd.data_source(id),
	lake_control_code_fs varchar,
	construction_year_ds uuid REFERENCES cabd.data_source(id),
	construction_year_fs varchar,
	assess_schedule_ds uuid REFERENCES cabd.data_source(id),
	assess_schedule_fs varchar,
	expected_life_ds uuid REFERENCES cabd.data_source(id),
	expected_life_fs varchar,
	maintenance_last_ds uuid REFERENCES cabd.data_source(id),
	maintenance_last_fs varchar,
	maintenance_next_ds uuid REFERENCES cabd.data_source(id),
	maintenance_next_fs varchar,
	function_code_ds uuid REFERENCES cabd.data_source(id),
	function_code_fs varchar,
	condition_code_ds uuid REFERENCES cabd.data_source(id),
	condition_code_fs varchar,
	construction_type_code_ds uuid REFERENCES cabd.data_source(id),
	construction_type_code_fs varchar,
	height_m_ds uuid REFERENCES cabd.data_source(id),
	height_m_fs varchar,
	length_m_ds uuid REFERENCES cabd.data_source(id),
	length_m_fs varchar,
	size_class_code_ds uuid REFERENCES cabd.data_source(id),
	size_class_code_fs varchar,
	spillway_capacity_ds uuid REFERENCES cabd.data_source(id),
	spillway_capacity_fs varchar,
	spillway_type_code_ds uuid REFERENCES cabd.data_source(id),
	spillway_type_code_fs varchar,
	reservoir_present_ds uuid REFERENCES cabd.data_source(id),
	reservoir_present_fs varchar,
	reservoir_area_skm_ds uuid REFERENCES cabd.data_source(id),
	reservoir_area_skm_fs varchar,
	reservoir_depth_m_ds uuid REFERENCES cabd.data_source(id),
	reservoir_depth_m_fs varchar,
	storage_capacity_mcm_ds uuid REFERENCES cabd.data_source(id),
	storage_capacity_mcm_fs varchar,
	avg_rate_of_discharge_ls_ds uuid REFERENCES cabd.data_source(id),
	avg_rate_of_discharge_ls_fs varchar,
	degree_of_regulation_pc_ds uuid REFERENCES cabd.data_source(id),
	degree_of_regulation_pc_fs varchar,
	provincial_flow_req_ds uuid REFERENCES cabd.data_source(id),
	provincial_flow_req_fs varchar,
	federal_flow_req_ds uuid REFERENCES cabd.data_source(id),
	federal_flow_req_fs varchar,
	catchment_area_skm_ds uuid REFERENCES cabd.data_source(id),
	catchment_area_skm_fs varchar,
	upstream_linear_km_ds uuid REFERENCES cabd.data_source(id),
	upstream_linear_km_fs varchar,
	hydro_peaking_system_ds uuid REFERENCES cabd.data_source(id),
	hydro_peaking_system_fs varchar,
	generating_capacity_mwh_ds uuid REFERENCES cabd.data_source(id),
	generating_capacity_mwh_fs varchar,
	turbine_number_ds uuid REFERENCES cabd.data_source(id),
	turbine_number_fs varchar,
	turbine_type_code_ds uuid REFERENCES cabd.data_source(id),
	turbine_type_code_fs varchar,
	up_passage_type_code_ds uuid REFERENCES cabd.data_source(id),
	up_passage_type_code_fs varchar,
	down_passage_route_code_ds uuid REFERENCES cabd.data_source(id),
	down_passage_route_code_fs varchar,
	passability_status_code_ds uuid REFERENCES cabd.data_source(id),
	passability_status_code_fs varchar,
	passability_status_note_ds uuid REFERENCES cabd.data_source(id),
	passability_status_note_fs varchar,
	capture_date_ds uuid REFERENCES cabd.data_source(id),
	capture_date_fs varchar,
	last_update_ds uuid REFERENCES cabd.data_source(id),
	last_update_fs varchar,
	comments_ds uuid REFERENCES cabd.data_source(id),
	comments_fs varchar,
	complete_level_code_ds uuid REFERENCES cabd.data_source(id),
	complete_level_code_fs varchar,
	original_point_ds uuid REFERENCES cabd.data_source(id),
	original_point_fs varchar
);





insert into dams.dams_medium_large_attribute_source
(cabd_id, dam_name_en_ds, dam_name_end_fs, dam_name_fr_ds, dam_name_fr_fs)
select cabd_id,
case when dam_name_en is not null then b.uuid else null end,
case when dam_name_en is not null then a.data_source_id else null end,
case when dam_name_fr is not null then b.uuid else null end,
case when dam_name_fr is not null then a.data_source_id else null end,

from
dams.dams_medium_large a 
left join cabd.data_source b where a.data_source = b.name
and a.data_source is not null;