-- add additional fields to data source table from documentation site
-- additional fields will be used for datasource api to populate documentation site

alter table cabd.data_source add column full_name varchar;
alter table cabd.data_source add column organization_name varchar;
alter table cabd.data_source add column data_source_category  varchar;
alter table cabd.data_source add column geographic_coverage varchar;
alter table cabd.data_source add column source_id_field varchar;
alter table cabd.data_source add column licence varchar;


UPDATE cabd.data_source SET licence='https://open.canada.ca/en/open-government-licence-canada', geographic_coverage='National', source_id_field='CGNDB_ID' WHERE name = 'nrcan_cgndb';
UPDATE cabd.data_source SET licence='https://open.canada.ca/en/open-government-licence-canada', geographic_coverage='National', source_id_field='feature_id' WHERE name = 'nrcan_canvec_mm';
UPDATE cabd.data_source SET licence='https://open.canada.ca/en/open-government-licence-canada', geographic_coverage='National', source_id_field='feature_id' WHERE name = 'nrcan_canvec_hyf';
UPDATE cabd.data_source SET licence='https://open.canada.ca/en/open-government-licence-canada', geographic_coverage='National', source_id_field='nid' WHERE name = 'nrcan_nhn';
UPDATE cabd.data_source SET licence='https://www.statcan.gc.ca/en/reference/licence', geographic_coverage='National', source_id_field='csduid' WHERE name = 'statscan_census_subs';
UPDATE cabd.data_source SET geographic_coverage='United States', source_id_field='federal_id' WHERE name = 'usace_nid';
UPDATE cabd.data_source SET geographic_coverage='Alberta', source_id_field='bf_id' WHERE name = 'aep_bf_hy';
UPDATE cabd.data_source SET geographic_coverage='British Columbia', source_id_field='fish_obstacle_point_id (note that this dataset does not have stable IDs)' WHERE name = 'bceccs_fiss';
UPDATE cabd.data_source SET geographic_coverage='British Columbia', source_id_field='objectid' WHERE name = 'bcflnrord_wris_pubdams';
UPDATE cabd.data_source SET geographic_coverage='British Columbia', source_id_field='objectid' WHERE name = 'bcflnrord_kml_pubdams';
UPDATE cabd.data_source SET geographic_coverage='British Columbia', source_id_field='obstruction_id' WHERE name = 'bcflnrord_fwa';
UPDATE cabd.data_source SET geographic_coverage='State of Maine, United States of America', source_id_field='unique_id' WHERE name = 'megis_impounds';
UPDATE cabd.data_source SET geographic_coverage='Manitoba', source_id_field='objectid' WHERE name = 'mi_prov_ww';
UPDATE cabd.data_source SET geographic_coverage='New Brunswick', source_id_field='nid' WHERE name = 'nberd_nbhn_mmh';
UPDATE cabd.data_source SET geographic_coverage='New Brunswick', source_id_field='nid' WHERE name = 'nberd_nbhn_ho';
UPDATE cabd.data_source SET geographic_coverage='Newfoundland and Labrador', source_id_field='dam_index_num' WHERE name = 'nleccm_nlpdi';
UPDATE cabd.data_source SET geographic_coverage='Nova Scotia', source_id_field='shape_fid' WHERE name = 'nse_td_wf';
UPDATE cabd.data_source SET geographic_coverage='Nova Scotia', source_id_field='dam_id_number' WHERE name = 'nse_wcsd_gfielding';
UPDATE cabd.data_source SET geographic_coverage='Ontario', source_id_field='ogf_id' WHERE name = 'mndmnrf_odi';
UPDATE cabd.data_source SET geographic_coverage='Ontario', source_id_field='ogf_id' WHERE name = 'mndmnrf_ohn';
UPDATE cabd.data_source SET geographic_coverage='Québec', source_id_field='numéro_barrage' WHERE name = 'qmelcc_repbarrages';
UPDATE cabd.data_source SET geographic_coverage='Saskatchewan', source_id_field='feature_id' WHERE name = 'skmoe_hydrography';
UPDATE cabd.data_source SET geographic_coverage='Saskatchewan', source_id_field='objectid' WHERE name = 'wsa_sk_owned_dams';
UPDATE cabd.data_source SET geographic_coverage='National' WHERE name = 'cwf';
UPDATE cabd.data_source SET geographic_coverage='Nova Scotia', source_id_field='fid' WHERE name = 'cwf_canfish';
UPDATE cabd.data_source SET geographic_coverage='Global', source_id_field='id_fao' WHERE name = 'fao_aquastat';
UPDATE cabd.data_source SET geographic_coverage='Global', source_id_field='grand_id' WHERE name = 'gdw_grand';
UPDATE cabd.data_source SET geographic_coverage='Global', source_id_field='dam_id' WHERE name = 'gdw_goodd';
UPDATE cabd.data_source SET geographic_coverage='Maritimes', source_id_field='unique_id' WHERE name = 'ncc_chu_ab';
UPDATE cabd.data_source SET geographic_coverage='Global', source_id_field='npdp_id' WHERE name = 'su_npdp';
UPDATE cabd.data_source SET geographic_coverage='Great Lakes Region', source_id_field='barrier_id' WHERE name = 'wid_fishwerks';
UPDATE cabd.data_source SET geographic_coverage='New Brunswick', source_id_field='nb_id' WHERE name = 'mrmaps_nbwf';
UPDATE cabd.data_source SET geographic_coverage='Nova Scotia', source_id_field='ns_id' WHERE name = 'mrmaps_nswf';
UPDATE cabd.data_source SET geographic_coverage='Lake Superior Watershed', source_id_field='bid' WHERE name = 'swp_lsdi';


UPDATE cabd.data_source SET data_source_category='Federal',organization_name='Natural Resources Canada (NRCan)' where name='nrcan_cgndb';
UPDATE cabd.data_source SET data_source_category='Federal',organization_name='Natural Resources Canada (NRCan)' where name='nrcan_cgndb';
UPDATE cabd.data_source SET data_source_category='Federal',organization_name='Natural Resources Canada (NRCan)' where name='nrcan_canvec_mm';
UPDATE cabd.data_source SET data_source_category='Federal',organization_name='Natural Resources Canada (NRCan)' where name='nrcan_canvec_hyf';
UPDATE cabd.data_source SET data_source_category='Federal',organization_name='Natural Resources Canada (NRCan)' where name='nrcan_nhn';
UPDATE cabd.data_source SET data_source_category='Federal',organization_name='Statistics Canada' where name='statscan_census_subs';
UPDATE cabd.data_source SET data_source_category='Federal',organization_name='United States Army Corps of Engineers' where name='usace_nid';
UPDATE cabd.data_source SET data_source_category='Provincial/State',organization_name='Alberta Environment and Parks (AEP)' where name='aep_bf_hy';
UPDATE cabd.data_source SET data_source_category='Provincial/State',organization_name='British Columbia Ministry of Environment and Climate Change Strategy' where name='bceccs_fiss';
UPDATE cabd.data_source SET data_source_category='Provincial/State',organization_name='British Columbia Ministry of Forests, Lands, Natural Resource Operations and Rural Development (FLNRORD)' where name='bcflnrord_wris_pubdams';
UPDATE cabd.data_source SET data_source_category='Provincial/State',organization_name='British Columbia Ministry of Forests, Lands, Natural Resource Operations and Rural Development (FLNRORD)' where name='bcflnrord_kml_pubdams';
UPDATE cabd.data_source SET data_source_category='Provincial/State',organization_name='British Columbia Ministry of Forests, Lands, Natural Resource Operations and Rural Development (FLNRORD)' where name='bcflnrord_fwa';
UPDATE cabd.data_source SET data_source_category='Provincial/State',organization_name='Maine Office of Geographic Information Systems' where name='megis_impounds';
UPDATE cabd.data_source SET data_source_category='Provincial/State',organization_name='New Brunswick Department of Natural Resources and Energy Development' where name='nberd_nbhn_mmh';
UPDATE cabd.data_source SET data_source_category='Provincial/State',organization_name='New Brunswick Department of Natural Resources and Energy Development' where name='nberd_nbhn_ho';
UPDATE cabd.data_source SET data_source_category='Provincial/State',organization_name='Newfoundland and Labrador Department of Environment and Climate Change' where name='nleccm_nlpdi';
UPDATE cabd.data_source SET data_source_category='Provincial/State',organization_name='Nova Scotia Department of Environment and Climate Change' where name='nse_td_wf';
UPDATE cabd.data_source SET data_source_category='Provincial/State',organization_name='Nova Scotia Department of Environment and Climate Change' where name='nse_wcsd_gfielding';
UPDATE cabd.data_source SET data_source_category='Provincial/State',organization_name='Ontario Ministry of Northern Development, Mines, Natural Resources and Forestry (MNDMNRF)' where name='mndmnrf_odi';
UPDATE cabd.data_source SET data_source_category='Provincial/State',organization_name='Ontario Ministry of Northern Development, Mines, Natural Resources and Forestry (MNDMNRF)' where name='mndmnrf_ohn';
UPDATE cabd.data_source SET data_source_category='Provincial/State',organization_name='Québec Ministère de l''Environnement et de la Lutte contre les changements climatiques' where name='qmelcc_repbarrages';
UPDATE cabd.data_source SET data_source_category='Academic Institution/NGO',organization_name='Canadian Wildlife Federation (CWF)' where name='cwf_canfish';
UPDATE cabd.data_source SET data_source_category='Academic Institution/NGO',organization_name='Canadian Wildlife Federation (CWF)' where name='cwf';
UPDATE cabd.data_source SET data_source_category='Academic Institution/NGO',organization_name='Food and Agriculture Organization (FAO) of the United Nations' where name='fao_aquastat';
UPDATE cabd.data_source SET data_source_category='Academic Institution/NGO',organization_name='Global Dam Watch' where name='gdw_grand';
UPDATE cabd.data_source SET data_source_category='Academic Institution/NGO',organization_name='Global Dam Watch' where name='gdw_goodd';
UPDATE cabd.data_source SET data_source_category='Academic Institution/NGO',organization_name='Nature Conservancy of Canada (NCC)' where name='ncc_chu_ab';
UPDATE cabd.data_source SET data_source_category='Academic Institution/NGO',organization_name='Stanford University' where name='su_npdp';
UPDATE cabd.data_source SET data_source_category='Academic Institution/NGO',organization_name='Superior Watershed Partnership and Land Conservancy' where name='swp_lsdi';
UPDATE cabd.data_source SET data_source_category='Academic Institution/NGO',organization_name='Wisconsin Institute for Discovery' where name='wid_fishwerks';
UPDATE cabd.data_source SET data_source_category='Miscellaneous',organization_name='MR Maps' where name='mrmaps_nbwf';
UPDATE cabd.data_source SET data_source_category='Miscellaneous',organization_name='MR Maps' where name='mrmaps_nswf';
UPDATE cabd.data_source SET data_source_category='Provincial',organization_name='Manitoba Department of Transportation and Infrastructure' where name='mi_prov_ww';
UPDATE cabd.data_source SET data_source_category='Provincial',organization_name='Saskatchewan Water Security Agency' where name='wsa_sk_owned_dams';
UPDATE cabd.data_source SET data_source_category='Provincial',organization_name='Saskatchewan Ministry of Environment' where name='skmoe_hydrography';
UPDATE cabd.data_source SET data_source_category='Federal',organization_name='Environment and Climate Change Canada' where name='ecc_ceaa_090152237';
UPDATE cabd.data_source SET data_source_category='Federal',organization_name='Fisheries and Oceans Canada (DFO)' where name='dfo_annu_rep_2003_4';
UPDATE cabd.data_source SET data_source_category='Federal',organization_name='Fisheries and Oceans Canada (DFO)' where name='dfo_babine_lake_1967';
UPDATE cabd.data_source SET data_source_category='Federal',organization_name='Fisheries and Oceans Canada (DFO)' where name='dfo_sawatsky_2016';
UPDATE cabd.data_source SET data_source_category='Federal',organization_name='Fisheries and Oceans Canada (DFO)' where name='sarpr_atlantic_wfish';
UPDATE cabd.data_source SET data_source_category='Federal',organization_name='Natural Resources Canada (NRCan)' where name='dfo_atl_sal_rehab_ns';
UPDATE cabd.data_source SET data_source_category='Federal',organization_name='Prairie Farm Rehabilitation Administration (PFRA)' where name='pfra_dams';
UPDATE cabd.data_source SET data_source_category='Provincial',organization_name='Alberta Ministry of Agriculture and Irrigation' where name='aafred_aii';
UPDATE cabd.data_source SET data_source_category='Provincial',organization_name='Alberta Ministry of Environment and Protected Areas (AEP)' where name='aep_dsm';
UPDATE cabd.data_source SET data_source_category='Provincial',organization_name='Alberta Ministry of Environment and Protected Areas (AEP)' where name='aep_fmo_berry_crk';
UPDATE cabd.data_source SET data_source_category='Provincial',organization_name='Alberta Ministry of Environment and Protected Areas (AEP)' where name='aep_tao_bow_riv_basin';
UPDATE cabd.data_source SET data_source_category='Provincial',organization_name='Alberta Ministry of Environment and Protected Areas (AEP)' where name='aep_cldps';

UPDATE cabd.data_source SET data_source_category='Provincial',organization_name='Alberta Ministry of Environment and Protected Areas (AEP)' where name='aep_fsm_moundred_res';
UPDATE cabd.data_source SET data_source_category='Provincial',organization_name='Alberta Ministry of Environment and Protected Areas (AEP)' where name='aep_fsm_open_crk';
UPDATE cabd.data_source SET data_source_category='Provincial',organization_name='Alberta Ministry of Environment and Protected Areas (AEP)' where name='aep_littlebow_res_fin_2020';
UPDATE cabd.data_source SET data_source_category='Provincial',organization_name='Alberta Natural Resources Conservation Board' where name='nrcb_earp_app9401';

UPDATE cabd.data_source SET data_source_category='Provincial',organization_name='Alberta Ministry of Environment and Protected Areas (AEP)' where name='asrd_bathym_chin';
UPDATE cabd.data_source SET data_source_category='Provincial',organization_name='Alberta Ministry of Environment and Protected Areas (AEP)' where name='asrd_bathym_forty_mile';

UPDATE cabd.data_source SET data_source_category='Provincial',organization_name='Alberta Ministry of Environment and Protected Areas (AEP)' where name='asrd_bathym_jensen';
UPDATE cabd.data_source SET data_source_category='Provincial',organization_name='Alberta Ministry of Environment and Protected Areas (AEP)' where name='asrd_bathym_keho';
UPDATE cabd.data_source SET data_source_category='Provincial',organization_name='Alberta Ministry of Environment and Protected Areas (AEP)' where name='asrd_bathym_newell';
UPDATE cabd.data_source SET data_source_category='Provincial',organization_name='Alberta Ministry of Environment and Protected Areas (AEP)' where name='asrd_bathym_mcgregor';
UPDATE cabd.data_source SET data_source_category='Provincial',organization_name='Alberta Ministry of Environment and Protected Areas (AEP)' where name='asrd_bathym_payne';
UPDATE cabd.data_source SET data_source_category='Provincial',organization_name='Alberta Ministry of Environment and Protected Areas (AEP)' where name='asrd_bathym_st_mary';
UPDATE cabd.data_source SET data_source_category='Provincial',organization_name='Alberta Ministry of Environment and Protected Areas (AEP)' where name='asrd_bathym_stafford';
UPDATE cabd.data_source SET data_source_category='Provincial',organization_name='Alberta Ministry of Environment and Protected Areas (AEP)' where name='asrd_bathym_travers';
UPDATE cabd.data_source SET data_source_category='Provincial',organization_name='BC Hydro' where name='bc_hydro_alouette';
UPDATE cabd.data_source SET data_source_category='Provincial',organization_name='BC Hydro' where name='bc_hydro_keenleyside';
UPDATE cabd.data_source SET data_source_category='Provincial',organization_name='BC Hydro' where name='bc_hydro_wwup_2022';
UPDATE cabd.data_source SET data_source_category='Provincial',organization_name='Newfoundland and Labrador Department of Environment and Climate Change' where name='nl_mae_permit_alt9067';
UPDATE cabd.data_source SET data_source_category='Provincial',organization_name='Newfoundland and Labrador Department of Environment and Climate Change' where name='nl_mae_permit_alt9371';
UPDATE cabd.data_source SET data_source_category='Provincial',organization_name='Nova Scotia Department of Agriculture' where name='ns_dykeland_sites';
UPDATE cabd.data_source SET data_source_category='Municipal',organization_name='City of Calgary, Alberta' where name='ab_cal_gdii';
UPDATE cabd.data_source SET data_source_category='Municipal',organization_name='City of Calgary, Alberta' where name='ab_cal_grdo';
UPDATE cabd.data_source SET data_source_category='Municipal',organization_name='City of Dawson Creek, British Columbia' where name='bc_dc_wqar2019';
UPDATE cabd.data_source SET data_source_category='Municipal',organization_name='Eastern Irrigation District, Alberta' where name='aeid_bassano';
UPDATE cabd.data_source SET data_source_category='Municipal',organization_name='Halifax Water' where name='ns_hal_clews_swpp';
UPDATE cabd.data_source SET data_source_category='Municipal',organization_name='Halifax Water' where name='ns_hal_p25_2021';
UPDATE cabd.data_source SET data_source_category='Municipal',organization_name='Halifax Water' where name='ns_hal_p24_2019';
UPDATE cabd.data_source SET data_source_category='Municipal',organization_name='Halifax Water' where name='ns_hal_hwirp_v3';
UPDATE cabd.data_source SET data_source_category='Energy Company',organization_name='FortisBC' where name='fortisbc_ops_hydro';
UPDATE cabd.data_source SET data_source_category='Energy Company',organization_name='Innergex' where name='innergex_douglas_creek';
UPDATE cabd.data_source SET data_source_category='Energy Company',organization_name='Irrican Power' where name='irrican_chin_chute';
UPDATE cabd.data_source SET data_source_category='Energy Company',organization_name='Irrican Power' where name='irrican_drops_456';
UPDATE cabd.data_source SET data_source_category='Energy Company',organization_name='Irrican Power' where name='irrican_ray_res';
UPDATE cabd.data_source SET data_source_category='Energy Company',organization_name='Lower Churchill Management Corporation' where name='lcmc_protulipac_et_al_2018';
UPDATE cabd.data_source SET data_source_category='Energy Company',organization_name='NB Power' where name='nbpower_hydro_tour';
UPDATE cabd.data_source SET data_source_category='Energy Company',organization_name='Newfoundland and Labrador Hydro' where name='nlhydro_adsr_2017_70503';
UPDATE cabd.data_source SET data_source_category='Energy Company',organization_name='Newfoundland and Labrador Hydro' where name='nlhydro_ca_nlh_155';
UPDATE cabd.data_source SET data_source_category='Energy Company',organization_name='Newfoundland and Labrador Hydro' where name='nlhydro_ops_hydro';
UPDATE cabd.data_source SET data_source_category='Energy Company',organization_name='Newfoundland Power' where name='nlp_depreciation_2019';
UPDATE cabd.data_source SET data_source_category='Energy Company',organization_name='Newfoundland Power' where name='nlp_dsi_2007';
UPDATE cabd.data_source SET data_source_category='Energy Company',organization_name='Newfoundland Power' where name='nlp_fac_rehab_2014';
UPDATE cabd.data_source SET data_source_category='Energy Company',organization_name='Newfoundland Power' where name='nlp_fac_rehab_2012';

UPDATE cabd.data_source SET data_source_category='Energy Company',organization_name='Newfoundland Power' where name='nlp_ppiep_2009';
UPDATE cabd.data_source SET data_source_category='Energy Company',organization_name='Newfoundland Power' where name='nlp_pub_safety_2016';
UPDATE cabd.data_source SET data_source_category='Energy Company',organization_name='Newfoundland Power' where name='nlp_rbfc_2011';
UPDATE cabd.data_source SET data_source_category='Energy Company',organization_name='Newfoundland Power' where name='nlp_sep_2008';
UPDATE cabd.data_source SET data_source_category='Energy Company',organization_name='Nova Scotia Power' where name='nsp_ihas';
UPDATE cabd.data_source SET data_source_category='Energy Company',organization_name='Suncor Energy' where name='suncor_safety_initiative';
UPDATE cabd.data_source SET data_source_category='Energy Company',organization_name='TransAlta' where name='transalta_barrier';
UPDATE cabd.data_source SET data_source_category='Energy Company',organization_name='TransAlta' where name='transalta_bearspaw';
UPDATE cabd.data_source SET data_source_category='Energy Company',organization_name='TransAlta' where name='transalta_belly';
UPDATE cabd.data_source SET data_source_category='Energy Company',organization_name='TransAlta' where name='transalta_bighorn';
UPDATE cabd.data_source SET data_source_category='Energy Company',organization_name='TransAlta' where name='transalta_brazeau';
UPDATE cabd.data_source SET data_source_category='Energy Company',organization_name='TransAlta' where name='transalta_cascade';
UPDATE cabd.data_source SET data_source_category='Energy Company',organization_name='TransAlta' where name='transalta_ghost';
UPDATE cabd.data_source SET data_source_category='Energy Company',organization_name='TransAlta' where name='transalta_horseshoe';
UPDATE cabd.data_source SET data_source_category='Energy Company',organization_name='TransAlta' where name='transalta_interlakes';
UPDATE cabd.data_source SET data_source_category='Energy Company',organization_name='TransAlta' where name='transalta_kananaskis';
UPDATE cabd.data_source SET data_source_category='Energy Company',organization_name='TransAlta' where name='transalta_pocaterra';
UPDATE cabd.data_source SET data_source_category='Energy Company',organization_name='TransAlta' where name='transalta_rundle';
UPDATE cabd.data_source SET data_source_category='Energy Company',organization_name='TransAlta' where name='transalta_sheerness';
UPDATE cabd.data_source SET data_source_category='Energy Company',organization_name='TransAlta' where name='transalta_spray';
UPDATE cabd.data_source SET data_source_category='Energy Company',organization_name='TransAlta' where name='transalta_st_mary';
UPDATE cabd.data_source SET data_source_category='Energy Company',organization_name='TransAlta' where name='transalta_taylor';
UPDATE cabd.data_source SET data_source_category='Energy Company',organization_name='TransAlta' where name='transalta_three_sisters';
UPDATE cabd.data_source SET data_source_category='Energy Company',organization_name='TransAlta' where name='transalta_waterton';
UPDATE cabd.data_source SET data_source_category='Academic Institution/NGO',organization_name='Alberta WaterPortal Society' where name='awps_brid';
UPDATE cabd.data_source SET data_source_category='Academic Institution/NGO',organization_name='Alberta WaterPortal Society' where name='awps_smrid';
UPDATE cabd.data_source SET data_source_category='Academic Institution/NGO',organization_name='Alberta Wilderness Association' where name='awa_obed_spill';
UPDATE cabd.data_source SET data_source_category='Academic Institution/NGO',organization_name='Shubenacadie Canal Commission' where name='scc_locks';
UPDATE cabd.data_source SET data_source_category='Academic Institution/NGO',organization_name='South East Alberta Watershed Alliance (SEAWA)' where name='seawa_pakowki_lake';
UPDATE cabd.data_source SET data_source_category='Consulting Company',organization_name='Advanced Construction Techniques Ltd.' where name='act_st_mary_spillway';
UPDATE cabd.data_source SET data_source_category='Consulting Company',organization_name='AECOM' where name='aecom_clwse_2016';
UPDATE cabd.data_source SET data_source_category='Consulting Company',organization_name='AMEC Americas Ltd.' where name='amec_frmp_2013';
UPDATE cabd.data_source SET data_source_category='Consulting Company',organization_name='AMEC Americas Ltd.' where name='amec_ssrba_wss';
UPDATE cabd.data_source SET data_source_category='Consulting Company',organization_name='East Coast Aquatics Inc.' where name='eca_bio_assess';
UPDATE cabd.data_source SET data_source_category='Consulting Company',organization_name='Golder Associates Inc.' where name='golder_genesee_2013';
UPDATE cabd.data_source SET data_source_category='Consulting Company',organization_name='Golder Associates Inc.' where name='golder_inv_nl_2016';
UPDATE cabd.data_source SET data_source_category='Consulting Company',organization_name='Golder Associates Inc.' where name='golder_inv_nl_2019';
UPDATE cabd.data_source SET data_source_category='Consulting Company',organization_name='Golder Associates Inc.' where name='golder_inv_nl_2017';
UPDATE cabd.data_source SET data_source_category='Consulting Company',organization_name='Limnotek Research and Development Inc. and Hupacasath First Nation' where name='limnotek_tselr_2006';
UPDATE cabd.data_source SET data_source_category='Consulting Company',organization_name='MPE Engineering Ltd.' where name='mpe_aep_prov_inventory';
UPDATE cabd.data_source SET data_source_category='Consulting Company',organization_name='Northwest Hydraulic Consultants' where name='nhc_mark_creek_2015';
UPDATE cabd.data_source SET data_source_category='Consulting Company',organization_name='Power Advisory LLC' where name='pallc_nl_elec';
UPDATE cabd.data_source SET data_source_category='Consulting Company',organization_name='SNC-Lavalin Group Inc.' where name='sncl_lower_churchill';
UPDATE cabd.data_source SET data_source_category='Consulting Company',organization_name='Golder Associates Inc.' where name='golder_gotsf_2020';
UPDATE cabd.data_source SET data_source_category='Peer-reviewed Articles',organization_name='Alberta Law Review' where name='alrs_spray_lakes';
UPDATE cabd.data_source SET data_source_category='Peer-reviewed Articles',organization_name='Canadian Geotechnical Journal' where name='cgj_williams_etal_1983';
UPDATE cabd.data_source SET data_source_category='Personal Communications',organization_name='Hillcrest Geographics' where name='pcom_sn_hc_2022';
UPDATE cabd.data_source SET data_source_category='Personal Communications',organization_name='Baker Creek Enhancement Society' where name='pcom_bm_bces_2023';
UPDATE cabd.data_source SET data_source_category='Personal Communications',organization_name='Lhtako Dene Nation' where name='pcom_jn_ldn_2023';

UPDATE cabd.data_source SET data_source_category='Personal Communications',organization_name='Souris and Area Branch of the PEI Wildlife Federation' where name='pcom_jm_sab_2023';
UPDATE cabd.data_source SET data_source_category='Miscellaneous',organization_name='Wikipedia' where name='wiki_dickson_dam';
UPDATE cabd.data_source SET data_source_category='Miscellaneous',organization_name='Wikipedia' where name='wiki_cdn_wfs';
UPDATE cabd.data_source SET data_source_category='Miscellaneous',organization_name='Wikipedia' where name='wiki_gs_bc';
UPDATE cabd.data_source SET data_source_category='Miscellaneous',organization_name='Wikipedia' where name='wiki_nb_hydro';
UPDATE cabd.data_source SET data_source_category='Miscellaneous',organization_name='Wikipedia' where name='wiki_lbr';

UPDATE cabd.data_source SET full_name='Canadian Geographical Names Database' where name='nrcan_cgndb';
UPDATE cabd.data_source SET full_name='CanVec Series - Manmade Features' where name='nrcan_canvec_mm';
UPDATE cabd.data_source SET full_name='CanVec Series - Hydrographic Features' where name='nrcan_canvec_hyf';
UPDATE cabd.data_source SET full_name='National Hydrographic Network (NHN)' where name='nrcan_nhn';
UPDATE cabd.data_source SET full_name='Intercensal - Census Subdivision Boundary Files' where name='statscan_census_subs';
UPDATE cabd.data_source SET full_name='National Inventory of Dams' where name='usace_nid';
UPDATE cabd.data_source SET full_name='Base Features Hydrography' where name='aep_bf_hy';
UPDATE cabd.data_source SET full_name='Provincial Obstacles to Fish Passage (FISS)' where name='bceccs_fiss';
UPDATE cabd.data_source SET full_name='BC Geographic Warehouse - Public Dams' where name='bcflnrord_wris_pubdams';
UPDATE cabd.data_source SET full_name='BC Public Dams KML' where name='bcflnrord_kml_pubdams';
UPDATE cabd.data_source SET full_name='Freshwater Atlas (FWA) Obstructions' where name='bcflnrord_fwa';
UPDATE cabd.data_source SET full_name='Impoundments and Dams' where name='megis_impounds';
UPDATE cabd.data_source SET full_name='New Brunswick Hydrographic Network (NBHN)' where name='nberd_nbhn_mmh';
UPDATE cabd.data_source SET full_name='New Brunswick Hydrographic Network (NBHN)' where name='nberd_nbhn_ho';
UPDATE cabd.data_source SET full_name='Provincial Dam Inventory (NLPDI)' where name='nleccm_nlpdi';
UPDATE cabd.data_source SET full_name='Topographic Database - Water Feature Points (a), Lines (b), Polygons (c)' where name='nse_td_wf';
UPDATE cabd.data_source SET full_name='Water Control Structure Database (accessed from Gillian Fielding unpublished thesis, 2011)' where name='nse_wcsd_gfielding';
UPDATE cabd.data_source SET full_name='Ontario Dam Inventory (ODI)' where name='mndmnrf_odi';
UPDATE cabd.data_source SET full_name='Ontario Hydro Network (OHN) - Hydrographic Points (a), Lines (b), Polygons (c)' where name='mndmnrf_ohn';
UPDATE cabd.data_source SET full_name='Répertoire des Barrages' where name='qmelcc_repbarrages';
UPDATE cabd.data_source SET full_name='CANFISHPASS Database (inherited from Cooke Lab - Carleton University)' where name='cwf_canfish';
UPDATE cabd.data_source SET full_name='Barrier points identified through visual inspection of satellite imagery' where name='cwf';
UPDATE cabd.data_source SET full_name='AQUASTAT Dam Database' where name='fao_aquastat';
UPDATE cabd.data_source SET full_name='Global Reservoir and Dam Database (GRanD)' where name='gdw_grand';
UPDATE cabd.data_source SET full_name='Global Georeferenced Database of Dams (GOODD)' where name='gdw_goodd';
UPDATE cabd.data_source SET full_name='Canadian Hydrologic Units - Aquatic Barriers' where name='ncc_chu_ab';
UPDATE cabd.data_source SET full_name='National Performance of Dams Program (NPDP) Dam Database' where name='su_npdp';
UPDATE cabd.data_source SET full_name='Lake Superior Dam Inventory (funded by the U.S Fish and Wildlife Service)' where name='swp_lsdi';
UPDATE cabd.data_source SET full_name='Fishwerks' where name='wid_fishwerks';
UPDATE cabd.data_source SET full_name='Waterfalls of New Brunswick' where name='mrmaps_nbwf';
UPDATE cabd.data_source SET full_name='Waterfalls of Nova Scotia' where name='mrmaps_nswf';
UPDATE cabd.data_source SET full_name='Manitoba Provincial Waterways' where name='mi_prov_ww';
UPDATE cabd.data_source SET full_name='WSA Owned Dams' where name='wsa_sk_owned_dams';
UPDATE cabd.data_source SET full_name='Saskatchewan Hydrography' where name='skmoe_hydrography';
UPDATE cabd.data_source SET full_name='Canadian Environmental Assessment Agency' where name='ecc_ceaa_090152237';
UPDATE cabd.data_source SET full_name='Administration and Enforcement of the Fish Habitat Protection and Pollution Prevention Provisions of the Fisheries Act (2003-2004 Annual Report to Parliament)' where name='dfo_annu_rep_2003_4';
UPDATE cabd.data_source SET full_name='Babine Lake Development Program for Sockeye Salmon' where name='dfo_babine_lake_1967';
UPDATE cabd.data_source SET full_name='Information in Support of a Recovery Potential Assessment of Bull Trout' where name='dfo_sawatsky_2016';
UPDATE cabd.data_source SET full_name='Recovery Strategy for the Atlantic Whitefish' where name='sarpr_atlantic_wfish';
UPDATE cabd.data_source SET full_name='Atlantic Salmon Rehabilitation Project' where name='dfo_atl_sal_rehab_ns';
UPDATE cabd.data_source SET full_name='PFRA Dam Inventory' where name='pfra_dams';
UPDATE cabd.data_source SET full_name='Alberta Irrigation Information' where name='aafred_aii';
UPDATE cabd.data_source SET full_name='Alberta Dam Safety Map' where name='aep_dsm';
UPDATE cabd.data_source SET full_name='Berry Creek (Carolside) Reservoir Fisheries Management Objectives' where name='aep_fmo_berry_crk';
UPDATE cabd.data_source SET full_name='Bow River Basin - TransAlta Operations' where name='aep_tao_bow_riv_basin';
UPDATE cabd.data_source SET full_name='Coal Lake Dam - Planning Study (Assessment of Spillway & Drainage/Seepage at Downstream Toe)' where name='aep_cldps';
UPDATE cabd.data_source SET full_name='Stocking Maps - Mound Red Reservoir' where name='aep_fsm_moundred_res';
UPDATE cabd.data_source SET full_name='Stocking Maps - Open Creek Reservoir' where name='aep_fsm_open_crk';
UPDATE cabd.data_source SET full_name='Little Bow Reservoir FIN Summary' where name='aep_littlebow_res_fin_2020';
UPDATE cabd.data_source SET full_name='Pine Coolee Water Management Project' where name='nrcb_earp_app9401';
UPDATE cabd.data_source SET full_name='Bathymetry of Chin Lakes, 1:20,000' where name='asrd_bathym_chin';
UPDATE cabd.data_source SET full_name='Bathymetry of Forty Mile Coulee Reservoir, 1:10,000' where name='asrd_bathym_forty_mile';
UPDATE cabd.data_source SET full_name='Bathymetry of Jensen (Pothole) Reservoir, 1:5,000' where name='asrd_bathym_jensen';
UPDATE cabd.data_source SET full_name='Bathymetry of Keho Lake, 1:10,000' where name='asrd_bathym_keho';
UPDATE cabd.data_source SET full_name='Bathymetry of Lake Newell, 1:15,000' where name='asrd_bathym_newell';
UPDATE cabd.data_source SET full_name='Bathymetry of McGregor Lake,1:20,000' where name='asrd_bathym_mcgregor';
UPDATE cabd.data_source SET full_name='Bathymetry of Payne Lake, 1:7500' where name='asrd_bathym_payne';
UPDATE cabd.data_source SET full_name='Bathymetry of St. Mary Reservoir, 1:15,000' where name='asrd_bathym_st_mary';
UPDATE cabd.data_source SET full_name='Bathymetry of Stafford Reservoir, 1:10,000' where name='asrd_bathym_stafford';
UPDATE cabd.data_source SET full_name='Bathymetry of Travers Reservoir, 1:15,000' where name='asrd_bathym_travers';
UPDATE cabd.data_source SET full_name='Alouette System' where name='bc_hydro_alouette';
UPDATE cabd.data_source SET full_name='Hugh Keenleyside Dam' where name='bc_hydro_keenleyside';
UPDATE cabd.data_source SET full_name='Wahleach Water Use Plan: Monitoring and Physical Works Program Synthesis Report' where name='bc_hydro_wwup_2022';
UPDATE cabd.data_source SET full_name='Permit to Alter a Body of Water - Permit No. ALT9067-2017' where name='nl_mae_permit_alt9067';
UPDATE cabd.data_source SET full_name='Permit to Alter a Body of Water - Permit No. ALT9371-2017' where name='nl_mae_permit_alt9371';
UPDATE cabd.data_source SET full_name='Working With the Tides - Dykeland Sites' where name='ns_dykeland_sites';
UPDATE cabd.data_source SET full_name='Glenmore Dam Infrastructure Improvements' where name='ab_cal_gdii';
UPDATE cabd.data_source SET full_name='Glenmore Reservoir Dam Operations' where name='ab_cal_grdo';
UPDATE cabd.data_source SET full_name='Drinking Water Quality Reports' where name='bc_dc_wqar2019';
UPDATE cabd.data_source SET full_name='Bassano Dam' where name='aeid_bassano';
UPDATE cabd.data_source SET full_name='Chain Lakes Emergency Water Supply Watershed Area - Source Water Protection Plan' where name='ns_hal_clews_swpp';
UPDATE cabd.data_source SET full_name='Chain Lake Dam and Pockwock Lake Dam - Consultant Services' where name='ns_hal_p25_2021';
UPDATE cabd.data_source SET full_name='Halifax Water Dam Safety Review' where name='ns_hal_p24_2019';
UPDATE cabd.data_source SET full_name='Integrated Resource Plan - Water System Review' where name='ns_hal_hwirp_v3';
UPDATE cabd.data_source SET full_name='Electrical Facilities and Operations' where name='fortisbc_ops_hydro';
UPDATE cabd.data_source SET full_name='Douglas Creek' where name='innergex_douglas_creek';
UPDATE cabd.data_source SET full_name='Chin Chute Power Plant' where name='irrican_chin_chute';
UPDATE cabd.data_source SET full_name='Drops 4, 5, and 6 Power Plant' where name='irrican_drops_456';
UPDATE cabd.data_source SET full_name='Raymond Reservoir Power Plant' where name='irrican_ray_res';
UPDATE cabd.data_source SET full_name='Muskrat Falls Dams - Cold Climate Considerations in Design and Construction' where name='lcmc_protulipac_et_al_2018';
UPDATE cabd.data_source SET full_name='Hydro Tour' where name='nbpower_hydro_tour';
UPDATE cabd.data_source SET full_name='Audit Dam Safety Review for Pudops Dam, North Salmon Dam and Spillway (RFP# 2017-70503)' where name='nlhydro_adsr_2017_70503';
UPDATE cabd.data_source SET full_name='Depreciation Methodology and Asset Service Lives' where name='nlhydro_ca_nlh_155';
UPDATE cabd.data_source SET full_name='Operations - Hydro Generation' where name='nlhydro_ops_hydro';
UPDATE cabd.data_source SET full_name='2019 Depreciation Study - Hydro Plant Decommissioning Report' where name='nlp_depreciation_2019';
UPDATE cabd.data_source SET full_name='Dam Safety Inspection Reports' where name='nlp_dsi_2007';
UPDATE cabd.data_source SET full_name='2014 Facility Rehabilitation' where name='nlp_fac_rehab_2014';
UPDATE cabd.data_source SET full_name='2012 Facility Rehabilitation' where name='nlp_fac_rehab_2012';
UPDATE cabd.data_source SET full_name='Potential Projects to Increase Energy Production' where name='nlp_ppiep_2009';
UPDATE cabd.data_source SET full_name='Public Safety Around Dams' where name='nlp_pub_safety_2016';
UPDATE cabd.data_source SET full_name='Rattling Brook Fisheries Compensation' where name='nlp_rbfc_2011';
UPDATE cabd.data_source SET full_name='Sustainable Electricity Program' where name='nlp_sep_2008';
UPDATE cabd.data_source SET full_name='Nova Scotia Power Incorporated Hydro Asset Study - Redacted' where name='nsp_ihas';
UPDATE cabd.data_source SET full_name='Investor Mining and Tailings Safety Initiative Disclosure Table' where name='suncor_safety_initiative';
UPDATE cabd.data_source SET full_name='Barrier Power Plant' where name='transalta_barrier';
UPDATE cabd.data_source SET full_name='Bearspaw Plant' where name='transalta_bearspaw';
UPDATE cabd.data_source SET full_name='Belly River Hydro Facility' where name='transalta_belly';
UPDATE cabd.data_source SET full_name='Bighorn Plant' where name='transalta_bighorn';
UPDATE cabd.data_source SET full_name='Brazeau Plant' where name='transalta_brazeau';
UPDATE cabd.data_source SET full_name='Cascade Plant' where name='transalta_cascade';
UPDATE cabd.data_source SET full_name='Ghost Plant' where name='transalta_ghost';
UPDATE cabd.data_source SET full_name='Horseshoe Plant' where name='transalta_horseshoe';
UPDATE cabd.data_source SET full_name='Interlakes Plant' where name='transalta_interlakes';
UPDATE cabd.data_source SET full_name='Kananaskis Plant' where name='transalta_kananaskis';
UPDATE cabd.data_source SET full_name='Pocaterra Plant' where name='transalta_pocaterra';
UPDATE cabd.data_source SET full_name='Rundle Plant' where name='transalta_rundle';
UPDATE cabd.data_source SET full_name='Sheerness Generating Station' where name='transalta_sheerness';
UPDATE cabd.data_source SET full_name='Spray Hydro Facility' where name='transalta_spray';
UPDATE cabd.data_source SET full_name='St. Mary Hydro Facility' where name='transalta_st_mary';
UPDATE cabd.data_source SET full_name='Taylor Hydro Facility' where name='transalta_taylor';
UPDATE cabd.data_source SET full_name='Three Sisters Plant' where name='transalta_three_sisters';
UPDATE cabd.data_source SET full_name='Waterton Hydro Facility' where name='transalta_waterton';
UPDATE cabd.data_source SET full_name='Bow River Irrigation District' where name='awps_brid';
UPDATE cabd.data_source SET full_name='St. Mary River Irrigation District' where name='awps_smrid';
UPDATE cabd.data_source SET full_name='News Release: 4 Years After Obed Spill, Questions Remain' where name='awa_obed_spill';
UPDATE cabd.data_source SET full_name='The Locks' where name='scc_locks';
UPDATE cabd.data_source SET full_name='Pakowki Lake Watershed Profile' where name='seawa_pakowki_lake';
UPDATE cabd.data_source SET full_name='St. Mary Dam Spillway Replacement Project' where name='act_st_mary_spillway';
UPDATE cabd.data_source SET full_name='Chapman Lake Water Supply Expansion Project Environmental Assessment' where name='aecom_clwse_2016';
UPDATE cabd.data_source SET full_name='Flood Risk Mapping Project' where name='amec_frmp_2013';
UPDATE cabd.data_source SET full_name='South Saskatchewan River Basin in Alberta: Water Supply Study' where name='amec_ssrba_wss';
UPDATE cabd.data_source SET full_name='Biological Assessment for Proposed Liverpool Wind Farm' where name='eca_bio_assess';
UPDATE cabd.data_source SET full_name='Genesee Cooling Pond Thermal and Water Quality Modelling Study' where name='golder_genesee_2013';
UPDATE cabd.data_source SET full_name='Inventory and Assessment of Dams in Eastern Newfoundland' where name='golder_inv_nl_2016';
UPDATE cabd.data_source SET full_name='Inventory and Assessment of Dams in Newfoundland and Labrador Year Three' where name='golder_inv_nl_2019';
UPDATE cabd.data_source SET full_name='Inventory and Assessment of Dams in Newfoundland and Labrador Year Two' where name='golder_inv_nl_2017';
UPDATE cabd.data_source SET full_name='Trophic status of Elsie Lake Reservoir' where name='limnotek_tselr_2006';
UPDATE cabd.data_source SET full_name='Provincial Inventory of Potential Water Storage Sites and Diversion Scenarios' where name='mpe_aep_prov_inventory';
UPDATE cabd.data_source SET full_name='Mark Creek Dam - 2015 Dam Safety Review' where name='nhc_mark_creek_2015';
UPDATE cabd.data_source SET full_name='Review of the Newfoundland and Labrador Electricity System' where name='pallc_nl_elec';
UPDATE cabd.data_source SET full_name='Lower Churchill Project Design Criteria' where name='sncl_lower_churchill';
UPDATE cabd.data_source SET full_name='2020 Annual Inspection Report: Greenhills Operations Tailings Storage Facility' where name='golder_gotsf_2020';
UPDATE cabd.data_source SET full_name='Sacrificing Fish for Power: A Legal History of the Spray Lakes Development' where name='alrs_spray_lakes';
UPDATE cabd.data_source SET full_name='Norris, S.' where name='pcom_sn_hc_2022';
UPDATE cabd.data_source SET full_name='Mills, B.' where name='pcom_bm_bces_2023';
UPDATE cabd.data_source SET full_name='Neustater, J.' where name='pcom_jn_ldn_2023';
UPDATE cabd.data_source SET full_name='MacKinnon, J.' where name='pcom_jm_sab_2023';
UPDATE cabd.data_source SET full_name='Dickson Dam' where name='wiki_dickson_dam';
UPDATE cabd.data_source SET full_name='List of Canadian Waterfalls' where name='wiki_cdn_wfs';
UPDATE cabd.data_source SET full_name='List of Generating Stations in British Columbia' where name='wiki_gs_bc';
UPDATE cabd.data_source SET full_name='List of Generating Stations in New Brunswick' where name='wiki_nb_hydro';
UPDATE cabd.data_source SET full_name='Little Bow Lake Reservoir' where name='wiki_lbr';
UPDATE cabd.data_source SET full_name='Monitoring and performance of an earth-fill dam in central Alberta' where name='cgj_williams_etal_1983';

UPDATE cabd.data_source foo
SET
    source = CASE WHEN b.source IS NOT NULL THEN b.source ELSE foo.source END,
    comments = CASE WHEN b.comments IS NOT NULL THEN b.comments ELSE foo.comments END,
    full_name = CASE WHEN b.full_name IS NOT NULL THEN b.full_name ELSE foo.full_name END,
    organization_name = CASE WHEN b.organization_name IS NOT NULL THEN b.organization_name ELSE foo.organization_name END,
    data_source_category = CASE WHEN b.data_source_category IS NOT NULL THEN b.data_source_category ELSE foo.data_source_category END
FROM source_data.historical_datasource_updates b 
WHERE b.name = foo.name;

alter table cabd.feature_types add column description varchar;
update cabd.feature_types set description = 'A dam is a structure that is constructed to divert or hold back water of a stream, river, or lake for a specific purpose, e.g., hydroelectricity, water storage, or flood control. These structures impede the ability of fish to travel upstream unless there is a fishway installed on the structure. In the CABD, dams are defined as: small dams (i.e., having a height of less than 5 m), medium dams (i.e., having a height between 5 and 15 m), and large dams (i.e., having height of 15 m or greater, or a height between 5 m and 15 m that impounds more than 3 million m3).<br><br>Currently, the CABD dams layer also includes other types of structures, including weirs, powerhouses, spillways, canals, and lateral structures (e.g., embankments or saddle dams). Some of these structures don’t necessarily fragment freshwater systems in the upstream-downstream plane. As such, these structures should not be used for connectivity network analyses or barrier prioritization exercises. These data points can be filtered out using the Used for Network Analysis field (``use_analysis = false`` in the data).' where type = 'dams';
update cabd.feature_types set description = 'A natural structure that may impede the ability of fish to travel upstream due to changes in elevation and increased flow velocity.' where type = 'waterfalls';
update cabd.feature_types set description = 'A structure that is constructed to facilitate the passage of fish up- and/or downstream of an aquatic barrier (e.g., a dam or waterfall).' where type = 'fishways';