-- ============================================================================
-- Backfill stream_order in stream_crossings.cwf_satellite_review
-- from CHyF Strahler order, via FDW.
--
-- Author: Katherine O'Hearn
-- Last updated: 2026-09-18
--
-- WHAT THIS DOES
--   For each modelled crossing in the listed work units that has no
--   stream_order in the satellite review table, find the NEAREST CHyF
--   flowpath segment within 0.0001 degrees (~11 m) and, if that segment's
--   Strahler order is greater than 1, write it to the review table.
--
-- MATCHING RULES (deliberate - do not change without reading the notes)
--   1. Tolerance is 0.0001 degrees (~11 m in EPSG 4617), NOT 0.001 (~100 m).
--      Modelled crossings are generated by intersecting road/rail against the
--      stream network, so they sit essentially on a flowpath. A wide tolerance
--      only pulls in confluence neighbours.
--
--   2. Match is NEAREST SEGMENT, not MAX(strahler_order) within tolerance.
--      Near a confluence a crossing can be within tolerance of both a small
--      tributary and the larger stream it joins. Taking the max silently
--      promotes headwater crossings to the order of the neighbouring stream.
--
--   3. The "> 1" test is applied to the CHOSEN match, NOT as a filter on
--      candidate segments. This is the important one. If you filter the cache
--      to strahler_order > 1 first, an order-1 crossing near a confluence
--      loses its correct match and silently inherits the higher order instead.
--      Order-1 crossings are meant to stay NULL.
--
-- PREREQUISITES
--   - public.eflowpath_properties_vw exists as a foreign table into chyf2
--     and exposes: id, aoi_id, strahler_order, geometry
--   - If CHyF geometry gains/loses dimensions, the foreign table column may
--     need relaxing:
--         ALTER FOREIGN TABLE public.eflowpath_properties_vw
--             ALTER COLUMN geometry TYPE geometry;
--     Symptom is: "Geometry has Z dimension but column does not"
--
-- HOW TO RUN
--   Run every step in the SAME session - the temp tables do not survive
--   a reconnect. Edit the work unit list in STEP 1 and nowhere else.
--
-- CAUTION
--   Do not create permanent tables named tmp_*. A permanent public.tmp_chyf_streams
--   will shadow or be shadowed by the temp table depending on search_path,
--   and you will silently query the wrong one. STEP 4 checks for this.
-- ============================================================================


-- ============================================================================
-- STEP 1: Define the work units  <<< THE ONLY PLACE YOU EDIT >>>
--
-- These codes are used for BOTH chyf_aoi.short_name and
-- modelled_crossings.nhn_watershed_id.
--
-- Currently excluded:
--   02SB000 - was missed when loading chyf2, pending reimport (2026-09-18)
-- ============================================================================

DROP TABLE IF EXISTS tmp_work_units;

CREATE TEMP TABLE tmp_work_units (code text PRIMARY KEY);

INSERT INTO tmp_work_units (code) VALUES
    ('01AA000'),('01AB000'),('01BB002'),('01BD000'),('01BG001'),('01BG002'),
    ('01BG003'),('01BH001'),('01BH002'),('0210001'),('0210002'),('0210003'),
    ('02MCA00'),('02MCD01'),('02OAA01'),('02OJ000'),('02PC000'),('02PE001'),
    ('02PE002'),('02PF000'),('02PG001'),('02PG002'),('02PH001'),('02QA001'),
    ('02QA002'),('02QA003'),('02QB001'),('02QB002'),('02QB003'),('02QC001'),
    ('02QC002'),('02RG002'),('02RH001'),('02RH002'),('02RH003'),('02RH004'),
    ('02SC001'),('02SC002'),('02TB000'),('02TC000'),('02TE000'),('02UA000'),
    ('02UB000'),('02UC000'),('02VA000'),('02WC000'),('02WD000'),('03FA001'),
    ('03JA001'),('03JA002'),('03JA003'),('03JA004'),('03JA005'),('03JB001'),
    ('03JB002'),('03JB003'),('03JB004'),('03KA001'),('03KA002'),('03KB001'),
    ('03KB002'),('03KB003'),('03KC000'),('03KE000'),('03MA002'),('03MB000'),
    ('03MD001'),('03MD002'),('03MD003');

ANALYZE tmp_work_units;


-- ============================================================================
-- STEP 2: Resolve work unit codes to CHyF AOI ids
--
-- chyf_aoi is a foreign table, so pull this small set over once.
-- Any code that does not resolve is reported - usually a naming difference
-- between NHN watershed id and CHyF short_name, or a work unit not yet
-- loaded into chyf2. Unresolved codes mean those crossings will get no match.
-- ============================================================================

DROP TABLE IF EXISTS tmp_aoi_ids;

CREATE TEMP TABLE tmp_aoi_ids AS
SELECT a.id
FROM public.chyf_aoi a
JOIN tmp_work_units w ON w.code = a.short_name;

CREATE INDEX tmp_aoi_ids_idx ON tmp_aoi_ids (id);

ANALYZE tmp_aoi_ids;

-- Expect requested = resolved. If not, run the query below it.
SELECT
    (SELECT COUNT(*) FROM tmp_work_units) AS requested,
    (SELECT COUNT(*) FROM tmp_aoi_ids)    AS resolved;

-- Which codes did not resolve in chyf2?
SELECT w.code AS unresolved_work_unit
FROM tmp_work_units w
LEFT JOIN public.chyf_aoi a ON a.short_name = w.code
WHERE a.id IS NULL
ORDER BY w.code;


-- ============================================================================
-- STEP 3: Cache the CHyF stream network locally
--
-- The AOI filter is injected as literal UUIDs via dynamic SQL. This is
-- deliberate: postgres_fdw cannot push a join against a LOCAL temp table down
-- to the remote server, so joining tmp_aoi_ids directly risks dragging the
-- whole national network across the wire before filtering. Literals guarantee
-- the filter reaches chyf2.
--
-- NOTE: there is intentionally NO strahler_order filter here. See rule 3 in
-- the header. The cache must contain order-1 segments.
--
-- ST_Force2D drops the Z ordinate added by the CHyF elevation processor.
-- Nothing downstream is 3D and it saves memory and index space.
--
-- This is the slow step - it is the only one that touches the FDW.
-- ============================================================================

DROP TABLE IF EXISTS tmp_chyf_streams;

DO $$
DECLARE
    aoi_literals text;
BEGIN
    SELECT string_agg(quote_literal(id::text), ',')
    INTO aoi_literals
    FROM tmp_aoi_ids;

    IF aoi_literals IS NULL THEN
        RAISE EXCEPTION 'No AOI ids resolved - check STEP 2 before continuing.';
    END IF;

    EXECUTE format($sql$
        CREATE TEMP TABLE tmp_chyf_streams AS
        SELECT
            v.id,
            v.strahler_order,
            ST_Force2D(v.geometry) AS geometry
        FROM public.eflowpath_properties_vw v
        WHERE v.aoi_id IN (%s)
          AND v.strahler_order IS NOT NULL
          AND v.geometry IS NOT NULL
    $sql$, aoi_literals);
END $$;

CREATE INDEX tmp_chyf_streams_geometry_gix
    ON tmp_chyf_streams
    USING GIST (geometry);

ANALYZE tmp_chyf_streams;


-- ============================================================================
-- STEP 4: Sanity checks on the cache
--
-- order_1_segments MUST be greater than zero. If it is zero, the cache was
-- built with a strahler_order > 1 filter and every result after this point
-- will be wrong. See rule 3 in the header.
--
-- resolved_schema should be a pg_temp_* schema, NOT public. If it says public,
-- you are reading a leftover permanent table - drop it and rerun STEP 3.
-- ============================================================================

SELECT
    COUNT(*)                                         AS total_segments,
    COUNT(*) FILTER (WHERE strahler_order = 1)       AS order_1_segments,
    MIN(strahler_order)                              AS min_order,
    MAX(strahler_order)                              AS max_order,
    COUNT(DISTINCT ST_SRID(geometry))                AS distinct_srids,
    MIN(ST_SRID(geometry))                           AS srid
FROM tmp_chyf_streams;

SELECT n.nspname AS resolved_schema
FROM pg_class c
JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE c.oid = 'tmp_chyf_streams'::regclass;

-- SRID must match the crossings table.
SELECT DISTINCT ST_SRID(geometry) AS crossings_srid
FROM modelled_crossings.modelled_crossings
WHERE nhn_watershed_id IN (SELECT code FROM tmp_work_units)
LIMIT 5;


-- ============================================================================
-- STEP 5: Refresh statistics on the local tables
-- ============================================================================

ANALYZE modelled_crossings.modelled_crossings;
ANALYZE stream_crossings.cwf_satellite_review;


-- ============================================================================
-- STEP 6: Preview - what would the update do?
--
-- Runs the exact matching logic as STEP 7 but writes nothing.
--
-- Interpreting the result:
--   would_update       crossings that will receive a stream_order
--   left_null_order1   crossings whose nearest segment is order 1
--                      These stay NULL by design. Expect this to be large -
--                      most road crossings are over headwater streams.
--   left_null_nomatch  no CHyF segment within ~11 m. Expect ~1%. A large
--                      number here means missing chyf2 coverage for some work
--                      unit, or the crossings are not snapped to this network.
--   total_scoped       must equal the sum of the three above
-- ============================================================================

WITH scoped AS (
    SELECT mc.cabd_id, mc.geometry
    FROM modelled_crossings.modelled_crossings mc
    JOIN tmp_work_units w ON w.code = mc.nhn_watershed_id
),
best_match AS (
    SELECT
        c.cabd_id,
        (SELECT s.strahler_order
         FROM tmp_chyf_streams s
         WHERE s.geometry && ST_Expand(c.geometry, 0.0001)
           AND ST_DWithin(s.geometry, c.geometry, 0.0001)
         ORDER BY s.geometry <-> c.geometry
         LIMIT 1) AS strahler_order
    FROM scoped c
)
SELECT
    COUNT(*) FILTER (WHERE strahler_order > 1)     AS would_update,
    COUNT(*) FILTER (WHERE strahler_order = 1)     AS left_null_order1,
    COUNT(*) FILTER (WHERE strahler_order IS NULL) AS left_null_nomatch,
    COUNT(*)                                       AS total_scoped
FROM best_match;

-- ============================================================================
-- STEP 6b: OPTIONAL - how many of those crossings are even in the review table?
--
-- If the update reports far fewer rows than STEP 6 predicted, the review table
-- probably does not contain these crossings yet. This is an issue that should be
-- resolved before proceeding - talk to Andrew.
-- ============================================================================

WITH scoped AS (
    SELECT mc.cabd_id
    FROM modelled_crossings.modelled_crossings mc
    JOIN tmp_work_units w ON w.code = mc.nhn_watershed_id
)
SELECT
    COUNT(*)                                             AS scoped_crossings,
    COUNT(csr.cabd_id)                                   AS present_in_review,
    COUNT(*) FILTER (WHERE csr.cabd_id IS NULL)          AS missing_from_review,
    COUNT(*) FILTER (WHERE csr.stream_order IS NOT NULL) AS already_populated
FROM scoped s
LEFT JOIN stream_crossings.cwf_satellite_review csr
  ON csr.cabd_id = s.cabd_id;


-- ============================================================================
-- STEP 7: Run the update
--
-- Uncomment BEGIN / COMMIT to keep a rollback option on the first run.
-- Row count should match would_update from STEP 6, or be lower if some review
-- rows already had a value or some crossings are not in the review table.
-- ============================================================================

-- BEGIN;

WITH scoped AS (
    SELECT mc.cabd_id, mc.geometry
    FROM modelled_crossings.modelled_crossings mc
    JOIN tmp_work_units w ON w.code = mc.nhn_watershed_id
),
best_match AS (
    SELECT
        c.cabd_id,
        (SELECT s.strahler_order
         FROM tmp_chyf_streams s
         WHERE s.geometry && ST_Expand(c.geometry, 0.0001)
           AND ST_DWithin(s.geometry, c.geometry, 0.0001)
         ORDER BY s.geometry <-> c.geometry
         LIMIT 1) AS strahler_order
    FROM scoped c
)
UPDATE stream_crossings.cwf_satellite_review csr
SET stream_order = bm.strahler_order
FROM best_match bm
WHERE csr.cabd_id = bm.cabd_id
  AND csr.stream_order IS NULL
  AND bm.strahler_order > 1;

-- COMMIT;


-- ============================================================================
-- STEP 8: Verify, by work unit
--
-- A work unit where assigned = 0 and missing equals its full count was almost
-- certainly not loaded into chyf2 - the same situation as 02SB000.
-- ============================================================================

SELECT
    mc.nhn_watershed_id,
    COUNT(*)                                             AS review_rows,
    COUNT(*) FILTER (WHERE csr.stream_order IS NOT NULL) AS assigned,
    COUNT(*) FILTER (WHERE csr.stream_order IS NULL)     AS missing
FROM stream_crossings.cwf_satellite_review csr
JOIN modelled_crossings.modelled_crossings mc
  ON mc.cabd_id = csr.cabd_id
JOIN tmp_work_units w
  ON w.code = mc.nhn_watershed_id
GROUP BY mc.nhn_watershed_id
ORDER BY missing DESC, mc.nhn_watershed_id;


-- ============================================================================
-- STEP 9: Clean up (optional - temp tables drop at session end anyway)
-- ============================================================================

-- DROP TABLE IF EXISTS tmp_chyf_streams;
-- DROP TABLE IF EXISTS tmp_aoi_ids;
-- DROP TABLE IF EXISTS tmp_work_units;
